github action 12

diff --git a/server/javascripts/Dockerfile b/server/javascripts/Dockerfile
--- a/server/javascripts/Dockerfile
+++ b/server/javascripts/Dockerfile
@@ -4,14 +4,11 @@ FROM node:16
 # Ishlash uchun direktoriyani o'rnatish
 WORKDIR /app
 
-# NPM cache'ni tozalash
-RUN npm cache clean --force
-
 # package.json va package-lock.json fayllarini nusxalash
 COPY package*.json ./
 
 # Npm kutubxonalarini o'rnatish
-RUN npm install
+RUN npm install || (echo "npm install failed"; exit 1)
 
 # Barcha kodni konteynerga nusxalash
 COPY . .
